apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-v2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.coder.com/v2
    chart: coder
    # renovate: datasource=helm depName=coder repository=https://helm.coder.com/v2
    targetRevision: 2.13.3
    helm:
      version: v3
      values: |-
        coder:
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-db-url
                  key: url
            - name: CODER_ACCESS_URL
              value: "https://coder.pve-talos-k8s.local"
          ingress:
            enable: true
            host: "coder.pve-talos-k8s.local"
            className: "nginx"
          service:
            type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  destination:
    namespace: coder
    server: https://kubernetes.default.svc