apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
        - image: cloudflare/cloudflared:2024.2.1
          name: cloudflared
          args:
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - run
            - --token
            - $(CLOUDFLARE_TUNNEL_TOKEN)
          ports:
            - containerPort: 2000
              name: http-metrics
          envFrom:
            - secretRef:
                name: cloudflared-secret
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
