apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coder/code-server.git
    path: ci/helm-chart
    # renovate: datasource=github-releases depName=coder/code-server
    targetRevision: v4.14.1
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: code-server
    server: https://kubernetes.default.svc