apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-state
  namespace: terraform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-state-role
  namespace: terraform
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get", "list", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "update", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-state-rolebinding
  namespace: terraform
subjects:
- kind: ServiceAccount
  name: terraform-state
  namespace: terraform
roleRef:
  kind: Role
  name: terraform-state-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-state-sa-token
  namespace: terraform
  annotations:
    kubernetes.io/service-account.name: terraform-state
type: kubernetes.io/service-account-token