{
 "title": "Airgradient",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CO2 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_rco2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PM2.5 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_pm02", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_atmp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airgradient_rhum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CO2 Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ppm2" } },
   "targets": [
    { "expr": "airgradient_rco2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PM2.5 Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "airgradient_pm02", "legendFormat": "__auto" }
   ]
  }
 ]
}