apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-szamszur-cloud
  namespace: kube-prometheus-stack
spec:
  dnsNames:
  - "grafana.szamszur.cloud"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: grafana-szamszur-cloud-tls