apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    # renovate: datasource=helm depName=kube-prometheus-stack repository=https://prometheus-community.github.io/helm-charts
    targetRevision: 78.5.0
    helm:
      version: v3
      values: |
        alertmanager:
          ingress:
            ingressClassName: nginx
            annotations: {}
            enabled: true
            hosts:
            - alert-manager.szamszur.cloud
            labels: {}
            pathType: ImplementationSpecific
            paths:
            - /
            tls:
              - secretName: alert-manager-szamszur-cloud-tls
                hosts:
                - alert-manager.szamszur.cloud
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: "pve-nvme-wd-blue"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          ingress:
            ingressClassName: nginx
            annotations: {}
            enabled: true
            hosts:
            - grafana.szamszur.cloud
            labels: {}
            path: /
            tls:
              - secretName: grafana-szamszur-cloud-tls
                hosts:
                - grafana.szamszur.cloud
        prometheus:
          ingress:
            ingressClassName: nginx
            annotations: {}
            enabled: true
            hosts:
            - prometheus.szamszur.cloud
            labels: {}
            pathType: ImplementationSpecific
            paths:
            - /
            tls:
              - secretName: prometheus-szamszur-cloud-tls
                hosts:
                - prometheus.szamszur.cloud
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "pve-nvme-wd-blue"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
            additionalScrapeConfigs:
            - job_name: airgradient
              metrics_path: /metrics
              scrape_interval: 30s
              static_configs:
              - targets:
                - 192.168.0.190:9926
              metric_relabel_configs:
              - source_labels: [ __name__ ]
                target_label: __name__
                replacement: airgradient_${1}
            - job_name: comin
              metrics_path: /metrics
              scrape_interval: 30s
              static_configs:
              - targets:
                - 192.168.20.200:4243
                - 192.168.20.60:4243
                - 192.168.20.61:4243
                - 192.168.20.62:4243
              metric_relabel_configs:
              - source_labels: [ __name__ ]
                target_label: __name__
                replacement: comin_${1}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc