apiVersion: v1
kind: Secret
metadata:
  name: terraform-state-sa-token
  namespace: terraform
  annotations:
    kubernetes.io/service-account.name: terraform-state
type: kubernetes.io/service-account-token
