apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-state-rolebinding
  namespace: terraform
subjects:
- kind: ServiceAccount
  name: terraform-state
  namespace: terraform
roleRef:
  kind: Role
  name: terraform-state-role
  apiGroup: rbac.authorization.k8s.io
