apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-state-role
  namespace: terraform
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get", "list", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "update", "delete", "list"]
