apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-szamszur-cloud
  namespace: argocd
spec:
  dnsNames:
  - "argocd.szamszur.cloud"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: argocd-szamszur-cloud-tls