apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buildbarn-szamszur-cloud
  namespace: buildbarn
spec:
  dnsNames:
  - "buildbarn.szamszur.cloud"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: buildbarn-szamszur-cloud-tls
