apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-home/gitops-controller
    repoURL: https://github.com/rszamszur/home-ops
    targetRevision: master
