apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-controller
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    # renovate: datasource=docker depName=ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.13.0
    helm:
      version: v3
      values: |-
        replicaCount: 3
        flags:
          excludeLabelPropagationPrefixes:
          - "argocd.argoproj.io/instance"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
    - ServerSideApply=true
  destination:
    namespace: gha-runner-controller
    server: https://kubernetes.default.svc
