apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-home-ops
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    # renovate: datasource=docker depName=ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    targetRevision: 0.13.0
    helm:
      version: v3
      values: |-
        githubConfigUrl: "https://github.com/rszamszur/home-ops"
        githubConfigSecret: gha-runner-home-ops-secret

        minRunners: 3
        maxRunners: 10

        runnerScaleSetName: pve-talos

        controllerServiceAccount:
          namespace: gha-runner-controller
          name: gha-runner-controller-gha-rs-controller

        containerMode:
          type: "kubernetes"
          kubernetesModeWorkVolumeClaim:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "local-path"
            resources:
              requests:
                storage: 2Gi
          kubernetesModeServiceAccount:
            annotations:

        template:
          spec:
            # initContainers:
            #   - name: kube-init
            #     image: harbor.puqu.io/rszamszur/actions-runner:latest
            #     command: ["sudo", "chown", "-R", "1001:123", "/home/runner/_work"]
            #     volumeMounts:
            #       - name: work
            #         mountPath: /home/runner/_work
            containers:
              - name: runner
                image: harbor.puqu.io/rszamszur/actions-runner:latest
                command: ["/home/runner/run.sh"]
                env:
                  - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                    value: "false"
                volumeMounts:
                  - name: docker-auth
                    mountPath: "/home/runner/.docker"
                    readOnly: true
            volumes:
              - name: docker-auth
                secret:
                  secretName: docker-auth
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  destination:
    namespace: gha-runner-home-ops
    server: https://kubernetes.default.svc
