apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/actions/actions-runner-controller/releases/download/v0.22.0/actions-runner-controller.yaml
- nixos-config-runner.yaml
