[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisor/supervisord.pid
loglevel=info

[program:fcgiwrap]
command=/usr/bin/spawn-fcgi -n -s /run/fcgiwrap/fcgiwrap.sock -u nonroot -g nonroot -- /usr/sbin/fcgiwrap
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/fcgiwrap-stdout.log
stderr_logfile=/var/log/supervisor/fcgiwrap-stderr.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx-stdout.log
stderr_logfile=/var/log/supervisor/nginx-stderr.log