apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-uploads
  namespace: trek
  labels:
    app: trek
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pve-nvme-wd-blue