apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: coder-db
    app.kubernetes.io/name: postgresql
  name: data-coder-db-postgresql-0
  namespace: coder
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pve-nvme-wd-blue
  volumeAttributesClassName: csi-proxmox-backup-disable