apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buildbuddy.szamszur.cloud
  namespace: buildbuddy
spec:
  dnsNames:
  - "buildbuddy.szamszur.cloud"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: buildbuddy.szamszur.cloud-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buildbuddy-grpc.szamszur.cloud
  namespace: buildbuddy
spec:
  dnsNames:
  - "buildbuddy-grpc.szamszur.cloud"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: buildbuddy-grpc.szamszur.cloud-tls
