apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    # renovate: datasource=helm depName=cert-manager repository=https://charts.jetstack.io
    targetRevision: 1.15.2
    helm:
      version: v3
      values: |
        namespace: "cert-manager"
        crds:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
    - ServerSideApply=true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc