name: "Label Sync"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths: 
      - ".github/labels.yaml"

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: .github/labels.yml

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yaml
          delete-other-labels: true