name: "Label Sync"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths: 
      - ".github/labels.yaml"

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          sparse-checkout: .github/labels.yml

      - name: Sync Labels
        uses: EndBug/label-sync@56ccbe98b802346e4909344c4bd7c5375d8e37a2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yaml
          delete-other-labels: true