name: "Labeler"

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@c5dadc2a45784a4b6adfcd20fea3465da3a5f904
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yaml