name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      coder: ${{ steps.filter.outputs.coder }}
      images: ${{ steps.filter.outputs.images }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            coder:
              - ".github/workflows/publish.yaml"
              - "terraform/coder/**"
            images:
              - ".github/workflows/publish.yaml"
              - "images/**"
              - "bazel/**"
              - "WORKSPACE"
              - ".bazelrc"
              - ".bazelversion"
  coder:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.coder == 'true' }}
    name: Publish Coder template
    runs-on: pve-talos
    strategy:
      matrix:
        template: ["k8s-ubuntu-nix", "k8s-ubuntu"]
    env:
      CODER_URL: https://coder.szamszur.cloud
      CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload templates
        run: bazel run //terraform/coder/${{ matrix.template }}:coder.publish
  image:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.images == 'true' }}
    name: Publish image
    runs-on: pve-talos
    strategy:
      matrix:
        image: ["actions-runner"]
    steps:
      - uses: actions/checkout@v4
      - name: Push image
        run: bazel run //images/${{ matrix.image }}:image.push