name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      coder: ${{ steps.filter.outputs.coder }}
      images: ${{ steps.filter.outputs.images }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          filters: |
            coder:
              - ".github/workflows/publish.yaml"
              - "terraform/coder/**"
            images:
              - ".github/workflows/publish.yaml"
              - "images/**"
              - "bazel/**"
              - "MODULE.bazel"
              - "MODULE.bazel.lock"
              - ".bazelrc"
              - ".bazelversion"
  coder:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.coder == 'true' }}
    name: Publish Coder template
    runs-on: pve-talos
    strategy:
      matrix:
        template: ["k8s-ubuntu-nix", "k8s-ubuntu"]
    env:
      CODER_URL: https://coder.szamszur.cloud
      CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Upload templates
        run: bazel --bazelrc=bazel/bazelrc/remote-execution.bazelrc run //terraform/coder/${{ matrix.template }}:coder.publish
  image:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.images == 'true' }}
    name: Publish image
    runs-on: pve-talos
    strategy:
      matrix:
        image: ["actions-runner"]
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Push image
        run: bazel --bazelrc=bazel/bazelrc/remote-execution.bazelrc run //images/${{ matrix.image }}:image.push