name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      coder: ${{ steps.filter.outputs.coder }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            coder:
              - "terraform/coder/k8s-ubuntu-nix/**"
  coder:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.coder == 'true' }}
    name: Publish Coder templates
    runs-on: pve-talos
    env:
      CODER_URL: https://coder.szamszur.cloud
      CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload templates
        run: bazel run //terraform/coder/k8s-ubuntu-nix:coder.publish
